<a href="https://colab.research.google.com/github/ugursirvermez/PyTorch_Education/blob/main/01_pyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Sun Jan 14 19:28:16 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
##Chapter 1: PyTorch Kodlamaya Giriş - 00. PyTorch Fundamentals
#Kaynak: www.learnpytorch.io/00_pytorch_fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Skaler
vector = torch.tensor([7,7])
vector.shape

torch.Size([2])

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Random Tensor
random = torch.rand(2,2)
random.ndim
random

tensor([[0.3933, 0.2381],
        [0.4212, 0.8490]])

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

random_img_size_tensor = torch.rand(size =(224, 224, 3)) #height, width, color channels
random_img_size_tensor.shape


torch.Size([224, 224, 3])

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

float32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32)
float16_tensor = float32_tensor.type(torch.float16)
float32_tensor * float16_tensor

tensor([ 9., 36., 81.])

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

int32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.int32)
float32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32)
int32_tensor * float32_tensor

tensor([ 9., 36., 81.])

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Çalışmayan matris çarpımı kodu
tensor= torch.rand(3,4)
torch.matmul(tensor, tensor)
#RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4) hatası verir

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Çalışan matris çarpımı kodu
tensor = torch.rand(3,6) #Birincinin sütunu
tensor2 = torch.rand(6,8) #İkincinin satırına eşit olmalı
print("1.Tensor:",tensor)
print("2.Tensor",tensor2)
print("Sonuc:",torch.matmul(tensor, tensor2))

1.Tensor: tensor([[0.8213, 0.4545, 0.3721, 0.9917, 0.3017, 0.2365],
        [0.6247, 0.5478, 0.8940, 0.5234, 0.3180, 0.6300],
        [0.5284, 0.9169, 0.3095, 0.5635, 0.3929, 0.7900]])
2.Tensor tensor([[0.8126, 0.9725, 0.6034, 0.9151, 0.3844, 0.9925, 0.9199, 0.5313],
        [0.1459, 0.4721, 0.0313, 0.2392, 0.9337, 0.6712, 0.4958, 0.2275],
        [0.1332, 0.2663, 0.3254, 0.4446, 0.6568, 0.1559, 0.8337, 0.6574],
        [0.1016, 0.2167, 0.3444, 0.3678, 0.8688, 0.9732, 0.3954, 0.5817],
        [0.5018, 0.4732, 0.7866, 0.2452, 0.9578, 0.9613, 0.5109, 0.4685],
        [0.5211, 0.0871, 0.7430, 0.8714, 0.1101, 0.0762, 0.0151, 0.3042]])
Sonuc: tensor([[1.1586, 1.4906, 1.3854, 1.6705, 2.1611, 2.4514, 1.8410, 1.5745],
        [1.2477, 1.4229, 1.5835, 1.9197, 2.1674, 1.9901, 1.9705, 1.6892],
        [1.2705, 1.4060, 1.5384, 1.8326, 2.2155, 2.1745, 1.6343, 1.4450]])
